### ISSUE TITLE
Missing long-press to show task manager

### ISSUE THREAD

**Issue by mikehenrty** [elin-moco/fxos-addon-draggable-home-btn#1]
To do so, you could detect a long tap and then fire the following event

```
window.dispatchEvent(new CustomEvent('taskmanagershow'));
```

**Comment by elin-moco** [comment]
I did have long press detection, and I'm using new CustomEvent('holdhome').
Just might need to adjust the threshold. 
Currently user will need to press carefully to avoid too much movement so that task manager will show up.
https://github.com/elin-moco/fxos-addon-draggable-home-btn/blob/master/index.js#L52-L57

**Comment by mikehenrty** [comment]
Ah, gotcha. Sounds tricky. Good luck!

**Comment by elin-moco** [comment]
I've modified index.js and updated the package.zip,
do I need to create pull request to update hackerplace?

**Comment by mikehenrty** [comment]
You don't have to open a PR to hackerplace, pushing to your gh-pages branch in this repo will be enough. However, if you submit a PR to hackerplace with your new commit hash, it helps me keep track of when and what changed so I can send out my email update to foxfooders. So it's not needed, but it's appreciated :)

**Comment by elin-moco** [comment]
Cool, thanks!

**Comment by mikehenrty** [comment]
Fixed!
